adding navbar
RajatKaushal3956/HOPE-Hub_Of_Professional_Educators pull request #11
Opened 2021-12-17 09:15 UTC by atulbansal4444

2021-12-17 14:12 UTC, RajatKaushal3956 commented on src/components/Header/NavBar.jsx
> +        <Container fluid style={{fontSize: 18, padding: 5, backgroundColor: 'grey', top: 5}}>
There is no need to use of container as we are going to hide the links

2021-12-17 14:14 UTC, RajatKaushal3956 requested changes
Please do the suggested changes

2021-12-18 19:45 UTC, atulbansal4444 commented on src/components/Header/NavBar.jsx
> +        <Container fluid style={{fontSize: 18, padding: 5, backgroundColor: 'grey', top: 5}}>
removed

2022-01-01 04:31 UTC, RajatKaushal3956 commented
Closing this PR don't need now

2022-01-01 04:31 UTC, closed without merging